-- MySQL Script generated by MySQL Workbench
-- Sat Aug 24 04:22:48 2024
-- Model: app-giras-indomito    Version: 1.0

-- SITIO WEB DE GIRAS INDOMITO

-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema app_giras_indomito
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema app_giras_indomito
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `app_giras_indomito` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `app_giras_indomito`;

-- -----------------------------------------------------
-- Table `app_giras_indomito`.`escalafones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_giras_indomito`.`escalafones`
(
    `id`     INT          NOT NULL,
    `codigo` VARCHAR(15) NULL,
    `nombre` VARCHAR(150) NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `cod_escalafon_UNIQUE` (`id` ASC) VISIBLE
)
    ENGINE = InnoDB;

INSERT INTO escalafones VALUES (1,'110100','Gral. Director');
INSERT INTO escalafones VALUES (2,'110100','Gral. Inspector');
INSERT INTO escalafones VALUES (3,'110100','General');


-- app_giras_indomito.usuario definition
CREATE TABLE IF NOT EXISTS `app_giras_indomito`.`usuario` (
  `correo` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `clave` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `nombre` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `apellido_paterno` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `apellido_materno` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `sexo` char(1) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `activo` tinyint NOT NULL DEFAULT '1',
  PRIMARY KEY (`correo`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO app_giras_indomito.usuario (correo,clave,nombre,apellido_paterno,apellido_materno,sexo,created_at,activo) VALUES
	 ('NIAMESVI3@GMAIL.COM','$argon2id$v=19$m=65536,t=3,p=4$MY7LFU6oVxLdQ4w026AlHA$gre6kRxyicusg84HiD186ALWq8dJHxVNE+iSV9Lnous','NICOLÁS','AMÉSTICA','VIDAL','M','2025-03-13 13:34:45',1);
